name: CodeProject AI.Server (CPU)
version: 0.1.13
url: https://hub.docker.com/r/codeproject/ai-server
#image: 
panel_icon: mdi:face-recognition
slug: ai.server
description: standalone open-source AI server
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
full_access: false
usb: true
video: true
ingress: false
privileged:
  - PERFMON
ports:
#  5000/tcp: 5000
  32168/tcp: 32168
ports_description:
#  5000/tcp: Web interface
  32168/tcp: Web interface
webui: "[PROTO:http]://[HOST]:[PORT:32168]/"

# map:
#   - share:rw

environment:
  HA_ADDON: "true"
#   DATA_DIR: "/share/ai-server/data"
#   MODULES_PATH: "/share/ai-server/modules"
#   OPT_PATH: "/share/ai-server/modules"  # New mapping

# options:
#   MODULES_PATH: "/share/ai-server/modules"
#   DATA_DIR: "/share/ai-server/data"
#   OPT_PATH: "/share/ai-server/modules"  # New mapping

# schema:
#   MODULES_PATH: str
#   DATA_DIR: str
#   OPT_PATH: str

