name: CodeProject AI.Server (CPU)
version: 0.1.2
url: https://hub.docker.com/r/codeproject/ai-server
#image: 
panel_icon: mdi:face-recognition
slug: ai.server
description: standalone open-source AI server
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
full_access: false
usb: true
video: true
ingress: false
privileged:
  - PERFMON
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: Web interface
webui: "[PROTO:http]://[HOST]:[PORT:5000]/"
map:
  - config:rw
  - share:rw  # Share folder can be used for persistent storage

environment:
  HA_ADDON: "true"
  DATA_DIR: "/share/ai-server/data"
  MODULES_PATH: "/share/ai-server/modules"
options:
  MODULES_PATH: "/share/ai-server/modules"
  DATA_DIR: "/share/ai-server/data"
schema:
  MODULES_PATH: str
  DATA_DIR: str
